CREATE TABLE IF NOT EXISTS `banking` (
`id` INT(11) NOT NULL AUTO_INCREMENT,
`charid` VARCHAR(50) NOT NULL,
`account` VARCHAR(50) NOT NULL,
`saving` VARCHAR(50) NOT NULL DEFAULT '0',
PRIMARY KEY (`id`)
);
CREATE TABLE IF NOT EXISTS `banking_logs` (
`id` INT(11) NOT NULL AUTO_INCREMENT,
`account` INT(50) NOT NULL,
`icon`  VARCHAR(100) NOT NULL,
`name`  VARCHAR(100) NOT NULL,
`amount`  VARCHAR(100) NOT NULL,
PRIMARY KEY (`id`)
);